### ISSUE TITLE
audit variable names

### ISSUE THREAD

**Issue by simonpcouch** [simonpcouch/forested#1]
I tried to rename variables in a way that makes their meanings a bit more self-evident, but may require some refinements.

**Comment by hfrick** [comment]
Nice renaming! 🙌  

`tree_no_tree` with levels `Yes` and `No` is a little confusing. Would levels `tree` and `no tree` work? I assume from the variable description that we want to keep the variable name as is?

**Comment by simonpcouch** [comment]
Good point—just adjusted those factor levels. That one still feels a bit wonky to me but :thinkies:

**Comment by simonpcouch** [comment]
This now feels good enough for me. Will go ahead and close but open to further conversation.
