### ISSUE TITLE
cite source data

### ISSUE THREAD

**Issue by simonpcouch** [simonpcouch/forested#3]
https://github.com/simonpcouch/forested/blob/46eaee215c0bdc042081f5cad8049273b556e8ab/R/forested.R#L50-L52

**Comment by simonpcouch** [comment]
Who could we cite for the raster layers, @graysonwhite?

**Comment by graysonwhite** [comment]
The raster layer citations are listed in [this article](https://arxiv.org/abs/2402.03263), noted in Table 1. That article might be a better one to cite for the data definitions as the current version of the Wieczorek paper doesn't include every auxiliary layer used in the `forested` dataset, but the one I linked above does. I also attached a bibtex with the references that are mentioned in Table 1 of the linked article for easy access. I also included a reference to the "green book", which is a great citation for FIA sampling design, procedures, etc. 

[references.txt](https://github.com/user-attachments/files/16316773/references.txt)

**Comment by simonpcouch** [comment]
Very much appreciated! :)
