### ISSUE TITLE
scale of temperature variables

### ISSUE THREAD

**Issue by simonpcouch** [simonpcouch/forested#4]
The temperatures are documented as degrees Celcius * 100. Why not just degrees Celcius?

**Comment by simonpcouch** [comment]
cc @graysonwhite, in case you have any input👀

**Comment by graysonwhite** [comment]
No idea why these are scaled this way -- I am sure it would be fine to rescale and document as degC. See attached metadata if helpful regarding variable scales, etc.! 

[FIESTA_auxiliary_metadata.xlsx](https://github.com/user-attachments/files/16316786/FIESTA_auxiliary_metadata.xlsx)

**Comment by simonpcouch** [comment]
Thank youuu!
